/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        ArrayList<String> test = new ArrayList<String>();
        test.add("Simon");
        IO.println(test.get(0));
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
