/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.List;
import org.example.expressions.Expression;

public class Lightcel {
    private final CsvReader csvr;
    private final Table table;
    private final Tokenizer tokenizer;
    private final Parser parser;
    private final Evaluator evaluator;

    public final String VERSION = "0.0.1";

    public Lightcel(CsvReader csvr, Table table, Tokenizer tokenizer, Parser parser, Evaluator evaluator) {
        this.csvr = csvr;
        this.table = table;
        this.tokenizer = tokenizer;
        this.parser = parser;
        this.evaluator = evaluator;
    }

    public void start(String[] args) {
        if (args.length == 0) {
            IO.println("usage: lightcel [-v | --version] [-h | --help] <command> [<args>]");
            return;
        }

        if (args.length > 2) {
            IO.println("usage: lightcel [-v | --version] [-h | --help] <command> [<args>]");
            return;
        }

        switch (args[0]) {
            case "-v", "--version" -> {
                IO.println("lightcel version " + VERSION);
            }

            case "-h", "--help" -> {
                IO.println("usage: lightcel [-v | --version] [-h | --help] <command> [<args>]\n");
                IO.println("How to use Lightcel:\n");
                IO.println("commands");
                IO.println("   parse   takes input.csv and produces output.csv with excel functionality");
            }

            case "parse" -> {
                if (args.length == 1) {
                    IO.println("usage: lightcel parse <input.csv>");
                    return;
                }

                if (args[1].equals("-h") || args[1].equals("--help")) {
                    IO.println("usage: lightcel parse <input.csv>");
                    return;
                }

                if (!args[1].toLowerCase().endsWith(".csv")) {
                    IO.println("lightcel: '" + args[1] + "' is not a CSV file. See 'lightcel --help'.");
                    return;
                }

                Path path = Path.of(args[1]);

                if (!Files.exists(path)) {
                    IO.println("lightcel: file '" + args[1] + "' does not exist.");
                    return;
                }

                if (!Files.isRegularFile(path)) {
                    IO.println("lightcel: '" + args[1] + "' is not a regular file.");
                    return;
                }

                csvr.importCsv(args[1]);
                printTable();
                createOutputFile();
            }

            default -> {
                IO.println("lightcel: '" + args[0] + "' is not a lightcel command. See 'lightcel --help'.");
            }
        }
    }

    void createOutputFile() {
        Path path = Paths.get("output.csv");
        try (BufferedWriter bw = Files.newBufferedWriter(path, StandardOpenOption.CREATE)) {
            String line = "";

            for (int row = 0; row <= table.getMaxInsertedRow(); row++) {
                for (int col = 0; col <= table.getMaxInsertedCol(); col++) {
                    Cell cell = table.getCell(row, col);
                    if (cell != null) {
                        CellType type = cell.getCellType();

                        String value = "";
                        if (cell.getValue() != null) {
                            value = cell.getValue().toString();
                        }

                        switch (type) {
                            case EMPTY -> line += ",";
                            case BOOLEAN -> {
                                line += value.toUpperCase() + ",";
                            }
                            case STRING, NUMBER -> line += value + ",";
                            case FORMULA -> {
                                List<Token> tokens = tokenizer.tokenize(value);
                                tokenizer.printTokenList(tokens);
                                Expression expr = parser.parse(tokens);
                                parser.printExpressionLog(expr);
                                String eval = evaluator.evaluate(expr);
                                line += eval + ",";
                            }
                        }
                    }
                }
                bw.write(line);
                bw.newLine();
                line = "";
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    void printTable() {
        IO.println("Printing Table Structure...\n");

        for (int row = 0; row <= table.getMaxInsertedRow(); row++) {
            for (int col = 0; col <= table.getMaxInsertedCol(); col++) {
                if (table.getCell(row, col) == null) {
                    IO.print("  ");
                } else {
                    IO.print(table.getCell(row, col).getValue() + "(" + table.getCell(row, col).getCellType() + ") ");
                }
            }
            if (row <= 2) {
                IO.println();
            }
        }

        IO.println("\n-------------------------------");
    }
}
