/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;

public class Lightcel {
    private Table<String> table;

    public Lightcel() {
        this.table = new Table<>("Numbers");
    }

    void main() {
        parseFile();
        printTable();
    }

    void parseFile() {
        String file = "/home/rain/programming/java/Lightcel/app/src/main/resources/input.csv";
        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
            int row = 0, col = 0;
            while ((line = br.readLine()) != null) {
                IO.println(line);
                String[] elements = line.split(",");
                for (String element : elements) {
                    if (element.startsWith("=SUM(")) {
                        
                    } else {
                        table.setCell(row, col, element);
                        col++;
                        IO.print(element + " ");
                    }
                }
                row++;
                col = 0;
                IO.println();
            }

        } catch (FileNotFoundException fnfe) {
            fnfe.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    void printTable() {
        for(int i = 0; i < Table.)
    }

}
